### ISSUE TITLE
ci(Compliance): make image cache working

### ISSUE THREAD

**Issue by ernado** [go-faster/oteldb#251]
This should work:

```yaml
- uses: docker/setup-buildx-action@v3

- name: Docker log in
  uses: docker/login-action@v3
  with:
    registry: ${{ env.REGISTRY }}
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}

- uses: actions/checkout@v4

- name: Build docker-compose
  # Before the cache, it was "run: docker compose build".
  working-directory: dev/local/ch-compliance
  run: docker buildx bake --file docker-compose.yml --file docker-compose-cache.json
```

But it is not: https://github.com/go-faster/oteldb/actions/runs/7151528767/job/19475919799

```
#12 [builder 2/6] WORKDIR /app
#12 DONE 2.1s

#13 [builder 3/6] COPY go.mod go.sum ./
#13 DONE 0.0s

#14 [builder 4/6] RUN go mod download
#14 DONE 11.2s

#15 [builder 5/6] COPY . ./
#15 DONE 0.4s
```

Should be `CACHED`.
