### ISSUE TITLE
feat: batching

### ISSUE THREAD

**Issue by ernado** [go-faster/oteldb#264]
We can't batch much on collector because of gRPC message size constraints (~4MB), but inserting to ClickHouse is better with larger batches.

So internal batching should be implemented.

For now it can be stateless and we accept possible data loss.

If possible and applicable, we can reuse otelcol's batch processor:

```yaml
batch:
  timeout: 500ms
  send_batch_max_size: 512
  send_batch_size: 256
```
